language: elixir
sudo: false

branches:
  only:
    - master
    - development

elixir:
  - 1.7.4
  - 1.8.0
  - 1.8.1
otp_release:
  - 21.0
  - 21.2

script: mix coveralls.travis
  - "MIX_ENV=test mix do deps.get, test && mix compile && mix coveralls.travis"
